import {
  pgTable,
  uuid,
  varchar,
  text,
  jsonb,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * ai_insights — structured data-driven insights derived from platform analytics.
 * Insights are generated by the AI from specific data patterns: e.g. "Strategy X
 * underperforms in high-volatility regimes" or "Concentration in BTC exceeds 40%".
 *
 * Unlike reports (narrative documents), insights are structured observations
 * with a domain, severity, and supporting data.
 *
 * Category: performance | risk | diversification | strategy | benchmark | allocation
 * Severity: info | warning | critical
 */
export const aiInsightsTable = pgTable(
  "ai_insights",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /** Insight category */
    category: varchar("category", { length: 50 }).notNull(),
    /** Severity: info | warning | critical */
    severity: varchar("severity", { length: 20 }).notNull().default("info"),
    /** Short title */
    title: varchar("title", { length: 255 }).notNull(),
    /** Full insight explanation */
    explanation: text("explanation").notNull(),
    /** Account ID if insight is account-scoped */
    accountId: uuid("account_id"),
    /** Strategy name if insight is strategy-scoped */
    strategyName: varchar("strategy_name", { length: 100 }),
    /** Supporting metrics/data */
    supportingData: jsonb("supporting_data"),
    /** Whether the user has acknowledged this insight */
    acknowledged: boolean("acknowledged").notNull().default(false),
    /** When acknowledged */
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    /** Source context snapshot */
    contextSnapshotId: uuid("context_snapshot_id"),
    /** Provider used */
    provider: varchar("provider", { length: 50 }).notNull().default("mock"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("ai_insights_category_idx").on(table.category),
    index("ai_insights_severity_idx").on(table.severity),
    index("ai_insights_account_idx").on(table.accountId),
    index("ai_insights_created_at_idx").on(table.createdAt),
    index("ai_insights_acknowledged_idx").on(table.acknowledged),
  ],
);

export const insertAiInsightSchema = createInsertSchema(aiInsightsTable).omit({
  id: true,
  createdAt: true,
});
export const selectAiInsightSchema = createSelectSchema(aiInsightsTable);

export type InsertAiInsight = z.infer<typeof insertAiInsightSchema>;
export type AiInsight = typeof aiInsightsTable.$inferSelect;
